Mathematically this looks like:

$$
\begin{align}
y &= f(w_1 x_1 + w_2 x_2 + b) \\
y &= f\left(\sum_i w_i x_i +b \right)
\end{align}
$$

With vectors this is the dot/inner product of two vectors:

$$
h = \begin{bmatrix}
x_1 \, x_2 \cdots  x_n
\end{bmatrix}
\cdot
\begin{bmatrix}
           w_1 \\
           w_2 \\
           \vdots \\
           w_n
\end{bmatrix}
$$

In [2]:
import torch

In [3]:
def activation(x):
  """
  Sigmoid activation funtion

  Arguments
  x: torch.Tensor
  """
  return 1/(1+torch.exp(-x))

Single layer neural network


In [4]:
# Generate some synthetic data

torch.manual_seed(7)
features = torch.randn((1, 5))
weights = torch.rand_like(features)
bias = torch.randn((1,1))

In [6]:
print(f"Features: {features}")
print(f"Weights: {weights}")
print(f"Bias: {bias}")

Features: tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
Weights: tensor([[0.2868, 0.2063, 0.4451, 0.3593, 0.7204]])
Bias: tensor([[-0.8948]])


In [7]:
# Calculating the output of the network using torch.sum()

y = activation(torch.sum(features * weights) + bias)
print(f"y = {y}")

y = tensor([[0.6140]])


In [8]:
# Calculating the output of the network using matrix multiplication

y = activation(torch.mm(features, weights.view(5, 1)) + bias)
print(f"y = {y}")

y = tensor([[0.6140]])


Multi layer neural network

In [9]:
## Generate some data
torch.manual_seed(7)

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in the network
n_input = features.shape[1]
n_hidden = 2
n_output = 1

# Weights for inputs to hidden layer
w1 = torch.randn(n_input, n_hidden)
# Weights for hidden to output layer
w2 = torch.randn(n_hidden, n_output)

# Bias for hidden and output layer
b1 = torch.randn((1, n_hidden))
b2 = torch.randn((1, n_output))


In [10]:
## Calculating the network output using matrix multiplication

h = activation(torch.mm(features, w1) + b1)
output = activation(torch.mm(h, w2) + b2)

print(f"y = {output}")

y = tensor([[0.3171]])


NumPy to Torch and back


In [11]:
import numpy as np

In [12]:
# Genarate some data

a = np.random.rand(4, 3)
print(a)

[[0.02622149 0.07555999 0.88539012]
 [0.97373152 0.32852534 0.76842735]
 [0.56931123 0.58401754 0.68909163]
 [0.88266498 0.87320229 0.4604449 ]]


In [13]:
# Convert numpy array to tensors

b = torch.from_numpy(a)
print(b)

tensor([[0.0262, 0.0756, 0.8854],
        [0.9737, 0.3285, 0.7684],
        [0.5693, 0.5840, 0.6891],
        [0.8827, 0.8732, 0.4604]], dtype=torch.float64)


In [14]:
# Convert tensors to numpy array

b.numpy()

array([[0.02622149, 0.07555999, 0.88539012],
       [0.97373152, 0.32852534, 0.76842735],
       [0.56931123, 0.58401754, 0.68909163],
       [0.88266498, 0.87320229, 0.4604449 ]])

The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [15]:
b.mul_(2)

tensor([[0.0524, 0.1511, 1.7708],
        [1.9475, 0.6571, 1.5369],
        [1.1386, 1.1680, 1.3782],
        [1.7653, 1.7464, 0.9209]], dtype=torch.float64)

In [16]:
print(a)

[[0.05244298 0.15111997 1.77078023]
 [1.94746303 0.65705068 1.5368547 ]
 [1.13862246 1.16803508 1.37818326]
 [1.76532995 1.74640458 0.92088979]]
